project:
  type: website
  output-dir: C:\Users\zj1026.stu\OneDrive - UBC\FCOR599\Term2\Guest Lecture\GuestLec3\E-Portfolio

website:
  title: "Your E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: publications.qmd
        text: Publications
      - href: content.qmd
        text: Content & Deliverables
      - href: contact.qmd
        text: Contact Info

format:
  html:
    theme: 
      - lumen
      - cerulean.scss
    css: styles.css
    toc: true
    fontsize: 1.1em
    linestretch: 1.7
    respect-user-color-scheme: true
    

    
editor: visual

