project:
  type: website
  output-dir: C:\Users\zj1026.stu\OneDrive - UBC\FCOR599\Term2\Guest Lecture\GuestLec3\E-Portfolio

website:
  title: "Your E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: publications.qmd
        text: Publications
      - href: content.qmd
        text: Content & Deliverables
      - href: contact.qmd
        text: Contact Info

format:
  html:
    theme:
      light: lumen
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
    smooth-scroll: true
    fontsize: 1.1em
    linestretch: 1.7
    code-fold: true
    code-tools: true
    highlight-style: github
    anchor-sections: true
    respect-user-color-scheme: true

    

    
editor: visual

